In [2]:
#Import Library
import numpy as np

In [3]:
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [4]:
#Checking numpy version
print(np.__version__)

2.3.0


In [5]:
#Print List 
list=[1,2,3,4]
print(list)

[1, 2, 3, 4]


In [7]:
#Tuple to array
a=np.array((10,20,30,40))
print(a)
print(type(a))

[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
# 0D Array
a=np.array(43)
print(a)

43


In [9]:
# 1D Array
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [11]:
#2D array
a=np.array([[10,20,30,40],
           [50,60,70,80]])
print(a)

[[10 20 30 40]
 [50 60 70 80]]


In [18]:
#3D Array
a=np.array([[[1,2,3],
             [4,5,6]],
             [[1,2,3],
             [4,5,6]]])
print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [23]:
#To check dimensionality
print(a.ndim)

3


In [24]:
#Access elements from array
a=np.array([10,20,30,40,50])
print(a[3])


40


In [33]:
#Access 2D array
a=np.array([[10,20,30,40,50],
           [50,60,70,80,90]])
print(a[0,2])


30


In [34]:
#2nd element omn 1st row
a=np.array([[1,2,3,4],
            [5,6,7,8]])
print("2nd element omn 1st row:",a[0,3])

2nd element omn 1st row: 4


In [35]:
#Negative Indexing
a=np.array([[1,2,3,4],
            [5,6,7,8]])
print(a[0,-2])
print(a[1,-3])


3
6


In [2]:
#Slicing array
import numpy as np
a=np.array([10,20,30,40,50])
print(a[1:3])


[20 30]


In [3]:
#Slicing array
a=np.array([10,20,30,40,50])
print(a[1:3:2])

[20]


In [67]:
#Negative slicing
a=np.array([10,20,30,40,50])
print(a[-3:-1])


[30 40]


In [6]:
#Dtype in array
a=np.array([10,20,30,40,50])
print(a.dtype)

int64


In [7]:
#Numpy array shape
a=np.array([[1,2,3,4],
            [5,6,7,8]])
print(a.shape)

(2, 4)


In [8]:
#Array array size
a=np.array([[1,2,3,4],
            [5,6,7,8]])
print(a.size)

8


In [15]:
#Reshape array
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=a.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
#Array iterating 
a=np.array([10,20,30,40,50])
for x in a:
    print(x)


10
20
30
40
50


In [64]:
#Joining Array
a=np.array([1,2,3])
a1=np.array([4,5,6])
a2=np.concatenate((a,a1))
print(a2)

[1 2 3 4 5 6]


In [25]:
#Spliting Array
a=np.array([10,20,30,40,50])
new_a=np.array_split(a,3)#return in no of rows 
print(new_a)


[array([10, 20]), array([30, 40]), array([50])]


In [26]:
#Searching for array
a=np.array([1,2,3,4,5,4,4])
x=np.where(a==4)#Print index where occurence 
print(x)

(array([3, 5, 6]),)


In [28]:
#Sorting for Array
a=np.array([4,6,2,5,9])
print(np.sort(a))#By default desc

#Descending
a=np.array([4,6,2,5,9])
print(np.sort(a)[::-1])#Negative slicing


[2 4 5 6 9]
[9 6 5 4 2]


In [31]:
#Filter Array
a=np.array([10,20,30,40,50])
x=[True,False,True,False,True]
new_a = a[x]
print(new_a)


[10 30 50]


In [36]:
#Access element using if-else
a=np.array([10,20,30,40,50])
filter_arr=[]
for element in a:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_a=a[filter_arr]
print(filter_arr)
print(new_a)
 


[False, False, False, False, True]
[50]


In [39]:
#Conversion of datatype
a=np.array([10,20,30,40,50])
print(a.astype(float))


[10. 20. 30. 40. 50.]


In [49]:
#adding and removing element
a=np.array([10,20,30,40,50])
print(np.append(a,[60,70,80,90,100]))#Add element Using append() 
print(np.insert(a,3,[60,70]))#Add element using insert() 
print(np.delete(a,[3]))#Removing element using delete()

[ 10  20  30  40  50  60  70  80  90 100]
[10 20 30 60 70 40 50]
[10 20 30 50]


In [50]:
#Aggregate functions
#Sum()
a=np.array([10,20,30,40,50])
print(np.sum(a))

150


In [51]:
#Min()
a=np.array([10,20,30,40,50])
print(np.min(a))

10


In [52]:
#Max()
a=np.array([10,20,30,40,50])
print(np.max(a))

50


In [53]:
#Cumsum
a=np.array([10,20,30,40,50])
print(np.cumsum(a))

[ 10  30  60 100 150]


In [56]:
#Stastical Functions
#Mean()
a=np.array([10,20,30,40,50,60])
print(np.mean(a))

35.0


In [57]:
#Median()
a=np.array([10,20,30,40,50,60])
print(np.median(a))

35.0


In [66]:
#Mode
from scipy import stats
a=np.array([10,20,30,40,50,60,20,30,20])
print(stats.mode(a))

ModeResult(mode=np.int64(20), count=np.int64(3))
